CREATE TABLE payment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date       TIMESTAMP,
    pay_option VARCHAR(255),
    amount     DECIMAL,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);